"""Faces Processor v1."""

PROCESSOR_NAME = "faces"
PROCESSOR_VERSION = "faces-v1"
CLUSTER_PROCESSOR_NAME = "faces-clustering"
CLUSTER_PROCESSOR_VERSION = "faces-clustering-v1"
RESULT_SCHEMA_VERSION = 1
SUPPORTED_WORKSPACE_CONTRACT_VERSION = 1
